=== alohaaloha/generated-app/XMLSchemas/NalogZaPrenos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.najjacabanka.com/"
            targetNamespace="http://www.najjacabanka.com/"
            elementFormDefault="qualified">
    <xs:element name="nalog-za-prenos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="duznik" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="svrha-placanja" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="poverilac" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="datum-prijema" type="xs:dateTime" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="mesto-prijema" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="datum-valute" type="xs:dateTime" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="racun-duznika" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="model-zaduzenja" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="poziv-na-broj-zaduzenja" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="racun-poverioca" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="model-odobrenja" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="poziv-na-broj-odobrenja" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="vrsta-placanja" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="valuta-placanja" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="iznos" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="hitno" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="tip-greske" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alohaaloha/generated-app/XMLDocuments/XMLNaloziZaPrenos/nalog_6.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- MODELUJE NALOG ZA PRENOS U IZMEDJU DJOKE KOJI DAJE NOVCE LANMIJU KOJI NIJE IZ ISTE BANKE
        STAVKA KLIRINGA -->

<nalog-za-prenos xmlns="http://www.najjacabanka.com/"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.najjacabanka.com/ file:/C:/Users/FS-LB/Desktop/PoslovnaInformatika/Projekat/pinf_pro/XMLSchemas/NalogZaPrenos.xsd">
    <duznik>Djoka Djokić</duznik>
    <svrha-placanja>Probno placanje medjubankarskog prenosa</svrha-placanja>
    <poverilac>Lanmi Trićmi</poverilac>
    <datum-prijema>2016-06-26T11:22:25</datum-prijema>
    <mesto-prijema>Novi Sad</mesto-prijema>
    <datum-valute>2016-06-25T06:00:00</datum-valute>
    <racun-duznika>001900000000000101</racun-duznika>
    <model-zaduzenja>97</model-zaduzenja>
    <poziv-na-broj-zaduzenja>3334444</poziv-na-broj-zaduzenja>
    <racun-poverioca>002900000000000202</racun-poverioca>
    <model-odobrenja>97</model-odobrenja>
    <poziv-na-broj-odobrenja>0001111</poziv-na-broj-odobrenja>
    <vrsta-placanja>287</vrsta-placanja>
    <valuta-placanja>RSD</valuta-placanja>
    <iznos>1000.00</iznos>
    <hitno>false</hitno>
    <tip-greske>0</tip-greske>
    <status></status>
</nalog-za-prenos>

=== alohaaloha/generated-app/XMLDocuments/XMLNaloziZaPrenos/nalog_2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- MODELUJE ISPLATNICU ANONIMUS UZIMA DJOKI FTN-U -->

<nalog-za-prenos xmlns="http://www.najjacabanka.com/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.najjacabanka.com/ file:/C:/Users/FS-LB/Desktop/PoslovnaInformatika/Projekat/pinf_pro/XMLSchemas/NalogZaPrenos.xsd">
    <duznik>Djoka DjokiÄ‡</duznik>
    <svrha-placanja>Probno placanje 2</svrha-placanja>
    <poverilac>Anonimus Anonimus</poverilac>
    <datum-prijema>2016-06-26T09:22:25</datum-prijema>
    <mesto-prijema>Novi Sad</mesto-prijema>
    <datum-valute>2016-06-25T06:00:00</datum-valute>
    <racun-duznika>001900000000000101</racun-duznika>
    <model-zaduzenja>97</model-zaduzenja>
    <poziv-na-broj-zaduzenja>2223333</poziv-na-broj-zaduzenja>
    <vrsta-placanja>287</vrsta-placanja>
    <valuta-placanja>RSD</valuta-placanja>
    <iznos>3.00</iznos>
    <hitno>0</hitno>
    <tip-greske>0</tip-greske>
    <status></status>
</nalog-za-prenos>

=== alohaaloha/generated-app/XMLDocuments/XMLNaloziZaPrenos/nalog_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- MODELUJE UPLATNICU DJOKA UPLACUJE JEVROSIMU FTN-U -->

<nalog-za-prenos xmlns="http://www.najjacabanka.com/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.najjacabanka.com/ file:/C:/Users/FS-LB/Desktop/PoslovnaInformatika/Projekat/pinf_pro/XMLSchemas/NalogZaPrenos.xsd">
    <duznik>Duznik Djoka</duznik>
    <svrha-placanja>Probno placanje</svrha-placanja>
    <poverilac>Poverilac Jevrosim FTN</poverilac>
    <datum-prijema>2016-06-25T09:22:25</datum-prijema>
    <mesto-prijema>Novi Sad</mesto-prijema>
    <datum-valute>2016-06-25T06:00:00</datum-valute>
    <racun-poverioca>840-0000001710666-12</racun-poverioca>
    <model-odobrenja>97</model-odobrenja>
    <poziv-na-broj-odobrenja>00-00000-0-0000-00000</poziv-na-broj-odobrenja>
    <vrsta-placanja>289</vrsta-placanja>
    <valuta-placanja>RSD</valuta-placanja>
    <iznos>4200.00</iznos>
    <hitno>nije</hitno>
    <tip-greske>0</tip-greske>
    <status></status>
</nalog-za-prenos>
